### ISSUE TITLE
IDE system fails with GPU

### ISSUE THREAD

**Issue by killah-t-cell** [SciML/NeuralPDE.jl#443] opened 2021-11-24 20:45 UTC
I adapted one of the IDE tests to the GPU, and ran into an error (likely related to get_numeric_integral or Quadrature). Seems like part of what we're broadcasting still contains a CPU array:

The error is 
```julia
ERROR: LoadError: GPU compilation of kernel broadcast_kernel(CUDA.CuKernelContext, SubArray{Float64, 1, CuDeviceVector{Float64, 1}, Tuple{CuDeviceVector{Int64, 1}}, false}, Base.Broadcast.Broadcasted{Nothing, Tuple{Base.OneTo{Int64}}, typeof(identity), Tuple{Base.Broadcast.Extruded{Vector{Float64}, Tuple{Bool}, Tuple{Int64}}}}, Int64) failed
KernelError: passing and using non-bitstype argument

Argument 4 to your kernel function is of type Base.Broadcast.Broadcasted{Nothing, Tuple{Base.OneTo{Int64}}, typeof(identity), Tuple{Base.Broadcast.Extruded{Vector{Float64}, Tuple{Bool}, Tuple{Int64}}}}, which is not isbits:
  .args is of type Tuple{Base.Broadcast.Extruded{Vector{Float64}, Tuple{Bool}, Tuple{Int64}}} which is not isbits.
    .1 is of type Base.Broadcast.Extruded{Vector{Float64}, Tuple{Bool}, Tuple{Int64}} which is not isbits.
      .x is of type Vector{Float64} which is not isbits.
```

and the MWE is

```julia
using Flux
using DiffEqFlux
using ModelingToolkit
using DiffEqBase
NeuralPDE
using GalacticOptim
using Optim
using Quadrature,Cubature, Cuba
using QuasiMonteCarlo
using SciMLBase
import ModelingToolkit: Interval, infimum, supremum
using DomainSets 
using CUDA

cb = function (p,l)
    println("Current loss is: $l")
    return false
end

@parameters x
@variables u(..) w(..)
Dx = Differential(x)
Ix = Integral(x in DomainSets.ClosedInterval(1, x))
# Iinf = Integral(x in DomainSets.ClosedInterval(1, Inf))

eqs =  [Ix(u(x)*w(x)) ~ log(abs(x)),
        Dx(w(x)) ~ -2/(x^3),
        u(x) ~ x ]

bcs = [u(1.) ~ 1.0, w(1.) ~ 1.0]
domains = [x ∈ Interval(1.0,2.0)]

chains = [FastChain(FastDense(1,15,Flux.σ),FastDense(15,1)) for _ in 1:2]
initθ = map(c -> CuArray(Float64.(c)), DiffEqFlux.initial_params.(chains))

strategy_ = NeuralPDE.GridTraining(0.1)
discretization = NeuralPDE.PhysicsInformedNN(chains,
                                             strategy_;
                                             init_params = initθ
                                             )
@named pde_system = PDESystem(eqs,bcs,domains,[x],[u(x), w(x)])
prob = NeuralPDE.discretize(pde_system,discretization)
res = GalacticOptim.solve(prob, BFGS(); cb = cb, maxiters=200)
```

**Comment by killah-t-cell** [comment] 2021-11-25 18:06
The stacktrace shows this is failing on this line:

https://github.com/SciML/NeuralPDE.jl/blob/a19c52cbf53a5ab9cbfb1609722a3fe10b2aa4ae/src/pinns_pde_solve.jl#L878

From there it goes to Quadrature, and then Cubature, and then it errors.

**Comment by ChrisRackauckas** [comment] 2022-06-29 10:35
All that's left is https://github.com/SciML/NeuralPDE.jl/issues/267, so closing as a duplicate of that issue.

**Closed by ChrisRackauckas** 2022-06-29 10:35 UTC
